---
title: "website versus azimuth"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(pheatmap)
library(gdata)
library(tidyr)
library(reshape2)
library(ggplot2)
library(plyr)
library(igraph)
library(RColorBrewer)
library(ggrepel)
library(gridExtra)
library(fossil)
library(e1071)
library(data.table)
library(ggpmisc)
library(ggpubr)

opts_chunk$set(echo = FALSE, warning = FALSE)
```

## Comparing With Web Predictions

```{r web_predicts}
website = read.csv('/Users/pdeweird/Documents/GPP-computation/Azimuth/azimuth/data/test200website.csv')
azimuth = read.csv('/Users/pdeweird/Documents/GPP-computation/Azimuth/azimuth/data/SpCas9_test_guides_azimuth_predictions.csv')
azimuth_website = inner_join(azimuth, website, by = c('kmer' = 'sgRNA.Context.Sequence'))
ggplot(azimuth_website) +
  aes(x=predicted, y=On.Target.Efficacy.Score) +
  geom_point() +
  xlab('Code Prediction') +
  ylab('Website Prediction') +
  coord_fixed()
ggsave('/Users/pdeweird/Documents/GPP-computation/Azimuth/azimuth/data/web_v_code.pdf')
```

## azimuth vs my own

```{r}
RS2_preds = read.csv(paste('/Users/pdeweird/Documents/csci-e-29/final_project-PeterDeWeirdt/data/predictions/PredictModel-',
                          '6095e6b4','.csv', sep = '')) %>%
  mutate(Model = 'RS2')
Dimer_preds = read.csv(paste('/Users/pdeweird/Documents/csci-e-29/final_project-PeterDeWeirdt/data/predictions/PredictModel-',
                          'febe0094','.csv', sep = '')) %>%
  mutate(Model = 'Dimer')
test_mat = read.csv('/Users/pdeweird/Documents/csci-e-29/final_project-PeterDeWeirdt/data/raw/SpCas9_test_guides.csv')
azimuth['Model'] = 'Azimuth'
```

#Both vs test data

```{r}
columnar_data = bind_rows(Dimer_preds, RS2_preds, azimuth) %>%
  inner_join(test_mat, by=c('kmer' = 'X30mer'))
columnar_data['true'] = round(columnar_data$true, 4) 
ggplot(columnar_data) +
  aes(x=true, y=predicted, color = Model) +
  theme(aspect.ratio = 1) +
  geom_point(alpha=0.5) +
  geom_smooth(method='lm', color = 'black') +
  stat_cor(method = 'spearman', color = 'black') +
  facet_wrap('Model') 
spread_data = spread(columnar_data %>% select(c('predicted', 'kmer', 'true', 'Model')), 'Model', 'predicted')
corr_map = melt(cor(spread_data %>% select(-'kmer'), method = 'spearman'))
corr_map['Var1'] = factor(corr_map$Var1, levels = c('Azimuth', 'RS2', 'Dimer', 'true'))
corr_map['Var2'] = factor(corr_map$Var2, levels = c('Azimuth', 'RS2', 'Dimer', 'true'))
corr_map
ggplot(corr_map) +
  aes(x=Var1, y=Var2, fill = value, label=round(value, 3)) +
  geom_tile(color = 'black') +
  scale_fill_gradient(low = 'lightyellow',high = 'red4', name = 'Spearman') +
  geom_text() +
  coord_equal() +
  xlab('') + 
  ylab('') 
ggsave(paste('/Users/pdeweird/Documents/csci-e-29/final_project-PeterDeWeirdt/data/figures/TrueV',hash,'.pdf', sep = ''), 
       height = 5, width = 7)
```

```{r}
baseline_correlation = test_mat %>%
  group_by(Gene) %>%
  dplyr::summarise(Rep.Spearman = cor(Rep.A.LFC.From.Dropout, Rep.B.LFC.From.Dropout, method = 'spearman'))
columnar_data['Model'] = factor(columnar_data$Model, levels = c('Azimuth', 'RS2', 'Dimer')) 
columnar_data %>%
  group_by(Model, Gene) %>%
  dplyr::summarise(spearman = cor(true, predicted, method = 'spearman')) %>%
  dplyr::inner_join(baseline_correlation, by = 'Gene') %>%
  mutate(Spearman.Fraction = spearman/Rep.Spearman) %>%
  ggplot() +
  aes(x=Gene, y=Model, fill=Spearman.Fraction, label=round(Spearman.Fraction, 3)) +
  geom_tile() +
  scale_fill_gradient(low = "lightyellow", high = 'darkred') +
  geom_text() +
  coord_equal()
ggsave(paste('/Users/pdeweird/Documents/csci-e-29/final_project-PeterDeWeirdt/data/figures/TrueV',hash,
       'Genes.pdf', sep=''), height = 5, width = 7)

```

```{r}
columnar_data %>%
  dplyr::mutate(d.LFC = abs(Rep.A.LFC.From.Dropout - Rep.B.LFC.From.Dropout), 
                d.prediction = abs(predicted - true)) %>%
  ggplot() +
  aes(x = d.LFC, y=d.prediction) +
  geom_point() +
  theme(aspect.ratio = 1) +
  stat_cor(method = 'spearman', color = 'blue') +
  geom_smooth(method = 'lm') +
  facet_wrap('Model')
```

